# Generated by Django 5.1.1 on 2024-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_currentjob_useraccount_currentlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='currentJob',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='currentLocation',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='shortDesc',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='StudentID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Token',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
