# Generated by Django 5.1.1 on 2024-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_useraccount_currentjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_SPSO',
            field=models.BooleanField(default=False),
        ),
    ]
