# Generated by Django 5.1.1 on 2024-12-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_useraccount_is_spso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='StudentID',
            new_name='studentID',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='Token',
            new_name='token',
        ),
    ]
