# Generated by Django 5.1.1 on 2024-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('TotalCost', models.PositiveIntegerField(default=0)),
                ('PaperType', models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4')], default='A4', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('SerialNumber', models.CharField(max_length=50)),
                ('ConnectionKey', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=50)),
                ('Building', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Printing', 'Printing'), ('Maintenance', 'Maintenance')], default='Available', max_length=50)),
            ],
        ),
    ]
