# Generated by Django 5.1.1 on 2024-12-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_rename_connectionkey_printer_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='PaperType',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='history',
            name='TotalCost',
        ),
        migrations.AddField(
            model_name='history',
            name='Copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='Cost',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='Direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='FileName',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='Pages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='Printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.printer'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
