# Generated by Django 5.1.1 on 2024-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0006_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllowedFiles', models.CharField(blank=True, max_length=255, null=True)),
                ('Token', models.PositiveIntegerField(default=1)),
                ('Time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
